services:
  amqpConfig:
    class: Config\AmqpConfig
  fileLocator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - ["./"]
  processor:
    class: Symfony\Component\Config\Definition\Processor
  yamlConfigLoader:
    class: Config\YamlConfigLoader
    arguments:
      - "@fileLocator"

  configuration.factory:
    class: Config\Processor
    arguments:
      - "@yamlConfigLoader"
      - "@fileLocator"
      - "@processor"

  amqpConfiguration:
    class: Array
    factory: ["@configuration.factory", getAmqpDefinition]
    arguments:
      - config
      - "@amqpConfig"

  amqpBuilder:
    class: Builder\Amqp
    arguments:
      - "@amqpConfiguration"