# declares all the configurations for all the listeners that we will use in the application
listener:
  listener:
    test:
      onProcessError: requeue
      maxRequeue:     3
      bulkAck:        50
