# defines all the monitors we want to use for the listeners along with their settings
services:
  # define monitors
  monitor.fileChange:
    class: \Amqp\Util\Monitor\FileChange

  monitor.memory:
    class: \Amqp\Util\Monitor\Memory
    calls:
      - [setLimit, [512M]]

  monitor.messageCounter:
    class: Amqp\Util\Monitor\MessageCounter
    calls:
      - [setLimit, [2000]]
