# declares all the configurations for all the listeners that we will use in the application
listener:
  listener:
    testQueue:
      onProcessError: requeue
      maxRequeue:     3
      bulkAck:        50
    dateTimeQueue:
      onProcessError: requeue
      maxRequeue:     3
      bulkAck:        50
