amqp:
  baseConnection:
    live: &baseLive {host: [localhost], port: 5672, login: admin, password: admin, vhost: /}

  baseChannel:
    base: &baseChannQOS {count: 100}

  baseExchange:
    base: &baseExchDurable {flags: [AMQP_DURABLE]}

  baseQueue:
    base: &baseQueueDurable {flags: [AMQP_DURABLE]}

  connection:
    live:
      <<:                   *baseLive
      login:                guest
      password:             guest

  channel:
    live:
      <<:                   *baseChannQOS
      connection:           live

  exchange:
    shop.club.dev:
      channel:              live
      <<:                   *baseExchDurable
      name:
        name:               shop.club.dev
        type:               constant
      type:                 AMQP_EX_TYPE_TOPIC
  queue:
    test:
      channel:              live
      <<:                   *baseQueueDurable
      name:
        type:               constant
        name:               test