listener:
  listener:
    consumer-test:
      # the queue on which we need to listen for incoming messages
      queue:                test-queue

      # behavior on failed process. Can be one of: requeue, error, stop, continue
      onProcessError:       requeue

      # if on processing we get an error, how many times we will requeue the message before not requeing it anymore
      maxRequeue:           3

      # bulk ack: the messages will only be acknowledged when the bulkack number has been hit
      bulkAck:              50