services:
  # define monitors
  monitor.fileChange:
    class: \Amqp\Util\Monitor\FileChange
    scope: prototype

  monitor.memory:
    class: \Amqp\Util\Monitor\Memory
    calls:
      - [setLimit, [512M]]
    scope: prototype

  monitor.messageCounter:
    class: Amqp\Util\Monitor\MessageCounter
    calls:
      - [setLimit, [2000]]
    scope: prototype
