services:
  # define all the types of publishers we need to use in the application
  publisher.type.demo:
    class: \Amqp\Util\Publisher\Rpc
    arguments:
      - @amqp.builder
    calls:
      - [attach, ["@processor.rpc"]]